name: LibreNMS-shibe
version: 1.0.0
appVersion: 1.0.0
description: Web publishing platform for building blogs and websites.
icon: https://i.imgur.com/3IiUmIp.png
keywords:
- nms
- monitoring
- http
- web
- application
- php
home: https://www.LibreNMS.org/
sources:
- https://github.com/librenms/docker
maintainers:
- name: shibe
  email: therealshibe@gmail.com
engine: gotpl
